export interface IContainerRecord {
    key: string,
    name: string,
    raw:any
}

export interface ITouchStoneContainer {
    "oid": string,
    "type": "Container",
    "modelDefinition": "ProductContainer",
    "modelIcon": string,
    "markForDelete": boolean,
    "owner": string,
    "createBy": string,
    "createDate": number,
    "updateBy": string,
    "updateDate": number,
    "tenantOid": string,
    "orderBy": number,
    "name": string,
    "productCatalogOid": string,
    "productCatalogName": string,
    "teamTemplateOid": string,
    "teamTemplateName": null | string,
    "containerTemplateOid": string,
    "containerTemplateName": null | string,
    "description": null | string,
    "productManagers": {
        "oid": string,
        "type": "User",
        "modelDefinition": "User",
        "modelIcon": null | string,
        "markForDelete": boolean,
        "owner": null | string,
        "createBy": string,
        "createDate": number,
        "updateBy": string,
        "updateDate": number,
        "tenantOid": string,
        "orderBy": number,
        "account": string,
        "name": string,
        "number": null | string,
        "password": null | string,
        "phone": string,
        "email": string,
        "gender": number,
        "description": null | string,
        "avatar": null | string,
        "signature": null | string,
        "disable": number,
        "securityLevel": number,
        "invalidTime": null | string
    }[],
    "team": null | string,
    "privateFlag": boolean,
    "extensionContent": null | string,
    "folder": null | string,
    "territory": null | string,
    "classify": null | string
}